### ISSUE TITLE
Finalize config file format

### ISSUE THREAD

**Issue by Brofessional** [mar-file-system/mad#4]
The config file format is up in the air right now. We need to get a final form so the config objects can be updated, and to fix any bugs that might be created by small name changes etc.

**Comment by jti-lanl** [comment]
JSON seems not-obviously-worse than XML (modulo the obvious shortcomings of JSON, like required quote-marks).

Something we would have to undertake, to make this change, is to write a tool to generate a ".h" file, translating the JSON into C-structs.  That might not be too big of a deal.  I think we currently depend on the "XML fingerprint" specification to support that.  This also buys us the potential for validating the config file.

**Comment by Brofessional** [comment]
@jti-lanl 
I believe the plan is to stick with an XML format. JSON had been discussed but XML holds a few advantages such comments. We also have other tools that use XML, so we don't need any extra tools to keep using it. But there are lots of options in config files that need cleaning up. Lots of values can be assumed and are no longer needed. Some values are simply not used or should be moved to a more fitting part of the config file. But we all probably need to sit in a room at some point and decide all that stuff together.

**Comment by Brofessional** [comment]
I found the format we are probably going to stick with. I've added it to the repo, and updated the data bindings to match it.
